from enum import Enum

class Screens(Enum):
    SPLASH = "SPLASH"
    MAIN = "MAIN"
    GRAFOS_EULER_1 = "GRAFOS_EULER_1"
    GRAFOS_EULER_2 = "GRAFOS_EULER_2"
    GRAFOS_EULER_3 = "GRAFOS_EULER_3"
    GRAFOS_HAMILTON_1 = "GRAFOS_HAMILTON_1"
    GRAFOS_HAMILTON_2 = "GRAFOS_HAMILTON_2"
    GRAFOS_HAMILTON_3 = "GRAFOS_HAMILTON_3"
    DIGRAFOS_EULER_1 = "DIGRAFOS_EULER_1"
    DIGRAFOS_HAMILTON_1 = "DIGRAFOS_HAMILTON_1"

