from enum import Enum

class Screens(Enum):
    SPLASH = "SPLASH"
    MAIN = "MAIN"
    INSTRUCTIONS = "INSTRUCTIONS"
    PLAYGROUND = "PLAYGROUND"
    PLAYGROUND_1 = "PLAYGROUND_1"
    PLAYGROUND_2 = "PLAYGROUND_2"
    PLAYGROUND_3 = "PLAYGROUND_3"
    PLAYGROUND_4 = "PLAYGROUND_4"
    PLAYGROUND_5 = "PLAYGROUND_5"
    MAP = "MAP"
    GRAFOS_EULER_1 = "GRAFOS_EULER_1"
    GRAFOS_EULER_2 = "GRAFOS_EULER_2"
    GRAFOS_EULER_3 = "GRAFOS_EULER_3"
    GRAFOS_HAMILTON_1 = "GRAFOS_HAMILTON_1"
    GRAFOS_HAMILTON_2 = "GRAFOS_HAMILTON_2"
    GRAFOS_HAMILTON_3 = "GRAFOS_HAMILTON_3"
    DIGRAFOS_EULER_1 = "DIGRAFOS_EULER_1"
    DIGRAFOS_HAMILTON_1 = "DIGRAFOS_HAMILTON_1"

