from enum import Enum


class Screens(Enum):
    SPLASH = "SPLASH"
    MAIN = "MAIN"
    MAP = "MAP"
    SELECT_YOUR_PET = "SELECT_YOUR_PET"
    INSTRUCTIONS = "INSTRUCTIONS"
    PLAYGROUND = "PLAYGROUND"
    PLAYGROUND_1 = "PLAYGROUND_1" # A-B-C-D-E
    PLAYGROUND_2 = "PLAYGROUND_2" # A-B-C-D-E-B-F-G-H-B-I-J-K
    PLAYGROUND_3 = "PLAYGROUND_3" # A-B-C-D-E
    PLAYGROUND_4 = "PLAYGROUND_4" # A-B-C-D-E-F-G-H
    PLAYGROUND_5 = "PLAYGROUND_5" # C-D-A-C-B-A-E-D
    INTRO_GRAPHS = "INTRO_EULER_PATH"
    INTRO_DIGRAPHS = "INTRO_HAMILTON_PATH"
    INTRO_EULER_PATH = "INTRO_EULER_CICLE"
    INTRO_HAMILTON_PATH = "INTRO_HAMILTON_CYCLE"
    GRAFOS_EULER_1 = "GRAFOS_EULER_1" # A-D-F-A-B-C-D-E
    GRAFOS_EULER_2 = "GRAFOS_EULER_2" # G-E-D-B-E-A-C-G-F-C-H
    GRAFOS_EULER_3 = "GRAFOS_EULER_3" # B-A-D-C-B-E-D-F-E-G-F-I-G-H-I-J
    GRAFOS_HAMILTON_1 = "GRAFOS_HAMILTON_1" # A-B-C-D-F-E-G-H
    GRAFOS_HAMILTON_2 = "GRAFOS_HAMILTON_2" # A-C-F-E-D-B-I-K-G-H-J-L
    GRAFOS_HAMILTON_3 = "GRAFOS_HAMILTON_3" # A-B-C-D-E-F-G-H-I-J-K-L-M-N-O-P
    DIGRAFOS_EULER_1 = "DIGRAFOS_EULER_1" # A-C-B-E-F-A-D
    DIGRAFOS_HAMILTON_1 = "DIGRAFOS_HAMILTON_1" # A-B-C-D-F-E-G-H
